spring:
  application:
    name: taco-cloud

  datasource:
    generate-unique-name: false
    name: taco-cloud
    url: jdbc:h2:mem:h2db
    driverClassName: org.h2.Driver
    username: user
    password: password

  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG